# Generated by Django 3.2.6 on 2023-02-01 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_userrestinfo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrestinfo',
            name='image',
        ),
    ]
