# Generated by Django 3.2.6 on 2023-02-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_userrestinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrestinfo',
            name='background_image',
            field=models.FileField(null=True, upload_to='user_image'),
        ),
        migrations.AddField(
            model_name='userrestinfo',
            name='profile_pic',
            field=models.FileField(null=True, upload_to='user_image'),
        ),
    ]
