# Generated by Django 3.2.6 on 2023-02-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230202_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrestinfo',
            name='about_me',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userrestinfo',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userrestinfo',
            name='city',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userrestinfo',
            name='country',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userrestinfo',
            name='postal_code',
            field=models.IntegerField(null=True),
        ),
    ]
